services:
  - type: web
    name: projexia-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: projexia-backend
          property: port
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: COOKIE_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

